### ISSUE TITLE
Crash when accessing guildmaster  on server

### ISSUE THREAD

**Issue by TheRanker** [Fulmineo64/Guild#8] opened 2021-09-22 18:56 UTC
**Modloader**
Did you experience the issue while playing on Fabric or on Forge?
Fabric 
**Describe the bug**
https://bytebin.lucko.me/Z5GoGpeUUR
**To Reproduce**
1. Go to '...'. Guild master
2. Click on '....' him
3. Scroll down to '....' crash to desktop 

**Expected behavior**
No crash
**Screenshots**

**Additional context**

**Comment by Anhelm** [comment] 2021-09-23 09:44
This error has been fixed in version 0.0.7
You are using version 0.0.5

**Comment by Fulmineo64** [comment] 2021-09-24 18:55
Hi TheRanker,
as Anhelm said, could you please update to the latest version and try again?
Thank you.

**Comment by Fulmineo64** [comment] 2021-10-02 11:33
Hi TheRanker.
I'm closing this for now.

If the problem is still present in the latest releases please open another issue.
Thank you!

**Closed by Fulmineo64** 2021-10-02 11:33 UTC
